version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mamhidet_mysql
    depends_on:
      - mysql
    volumes:
      - .:/app
    command: ["/app/wait-for-it.sh", "mysql", "3306", "--", "flet", "run", "main.py", "--web", "-p", "8000"]
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mamhidet_mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: