"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%kf$rb=_=e4r+xin!j=4+h@fj@d=v8=(=yew4v90#moj%9rqe&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AI_review',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gemini_programming',
        'USER': 'root',
        'PASSWORD': 'mamhidet_mysql',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'brain_knock': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gemini_brain_knock',
        'USER': 'root',
        'PASSWORD': 'mamhidet_mysql',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'business': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gemini_business_sujest',
        'USER': 'root',
        'PASSWORD': 'mamhidet_mysql',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'parse': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gemini_parse',
        'USER': 'root',
        'PASSWORD': 'mamhidet_mysql',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'mail': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gemini_mail',
        'USER': 'root',
        'PASSWORD': 'mamhidet_mysql',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'recipe': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gemini_recipe',
        'USER': 'root',
        'PASSWORD': 'mamhidet_mysql',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'translation': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gemini_translation',
        'USER': 'root',
        'PASSWORD': 'mamhidet_mysql',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'youtube': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gemini_youtube',
        'USER': 'root',
        'PASSWORD': 'mamhidet_mysql',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
