# Generated by Django 5.1.7 on 2025-03-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aireview',
            options={'managed': False},
        ),
    ]
